### ISSUE TITLE
Adapter stays yellow, no BT devise found 

### ISSUE THREAD

**Issue by Track4123** [mrbungle64/ioBroker.switchbot-ble#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hi. After updating the NPM the Adapter stand yellow, no BT devise is found. Tried already the reinstall and followed the recommendations in the fix issues, no success. What can this be?

### Version of the JS controller

10.8.2

### Version of Node.js

20.18.1

### Operating system

Linux

**Comment by Track4123** [comment]
@mrbungle64 keine Idee? Ist leider Schade das es nicht mehr funktioniert.
Dachte kann mir die Bridge sparen...

**Comment by mrbungle64** [comment]
@Track4123 

Probier mal ein `npm install` von bluetooth-hci-socket:

```bash
cd /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/
npm install
```

**Comment by MagicPST** [comment]
Habe das gleiche Problem ! Habe bluetooth-hci-socket neu installiert. Im log tauchen keine Fehler auf.Aber er findet nichts.
Das ganze ist erst jetzt aufgetreten nach einem update und upgrade der ubuntu systems   Ubuntu 20.04.6 LTS 
Node.js v20.18.1  NPM 10.8.2

**Comment by Track4123** [comment]
@mrbungle64, hab ich gemacht, leider kein Erfolg😩 sagt dir der Log was, z.B. die Warning? 
![Uploading E3E20602-1A8A-4EC2-B67D-9641BA94FCC6.jpeg…]()

**Comment by mrbungle64** [comment]
@Track4123 

Propier noch mal ein `rebuild` von bluetooth-hci-socket und noble

```bash
cd /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/
npm rebuild bluetooth-hci-socket
npm rebuild noble
```

Btw: Bitte keine Screenshots. Damit kann man kein Copy'n'Paste machen, wenn es mal notwendig ist

**Comment by Track4123** [comment]
@mrbungle64 , danke.
Habe ich beides gemacht, beides succesfully.
Danach habe ich den raspberry nochmal neu gestartet, kein Änderung, Adapter noch gelb.

**Comment by Track4123** [comment]
@mrbungle64 , hast du noch eine Idee was es sein kann? Habe meines Wissens alles Mögliche geprüft und ich bin auch nicht der Einzige mit dem Problem😥🫣🤔

**Comment by mrbungle64** [comment]
@Track4123 

> @mrbungle64 , hast du noch eine Idee was es sein kann? Habe meines Wissens alles Mögliche geprüft und ich bin auch nicht der Einzige mit dem Problem😥🫣🤔

Leider nein. Ich sehe in deinen Screenshots auch keinen Fehler (Warnings sind keine Fehler).
Du müsstest noch mal eine vollständige Log-Ausgabe als Text posten. Vielleicht ist da mehr zu sehen.

**Comment by Track4123** [comment]
hi. here we are:

Adapter Installation:

$ iobroker url https://github.com/mrbungle64/ioBroker.switchbot-ble --host iobroker --debug
install mrbungle64/ioBroker.switchbot-ble#3e7cf9932d474a2d5b6ece92c96c1a36bb90d329
NPM version: 10.8.2
Installing mrbungle64/ioBroker.switchbot-ble#3e7cf9932d474a2d5b6ece92c96c1a36bb90d329... (System call)
npm warn skipping integrity check for git dependency ssh://git@github.com/mrbungle64/ioBroker.switchbot-ble.git
> @abandonware/bluetooth-hci-socket@0.5.3-12 install> node-pre-gyp install --build-from-source
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node@20.18.1 | linux | arm64
node-pre-gyp info build requesting source compile
gyp info it worked if it ends with okgyp info using node-gyp@10.1.0gyp info using node@20.18.1 | linux | arm64
gyp info ok
gyp info it worked if it ends with okgyp info using node-gyp@10.1.0gyp info using node@20.18.1 | linux | arm64
gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',gyp info spawn args 'binding.gyp',gyp info spawn args '-f',gyp info spawn args 'make',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/build/config.gypi',gyp info spawn args '-I',gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',gyp info spawn args '-I',gyp info spawn args '/home/iobroker/.cache/node-gyp/20.18.1/include/node/common.gypi',gyp info spawn args '-Dlibrary=shared_library',gyp info spawn args '-Dvisibility=default',gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/20.18.1',gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/20.18.1/<(target_arch)/node.lib',gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket',gyp info spawn args '-Dnode_engine=v8',gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0gyp info using node@20.18.1 | linux | arm64
gyp info spawn make
make: Entering directory '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/build' CXX(target) Release/obj.target/bluetooth_hci_socket/src/BluetoothHciSocket.ogyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from /home/iobroker/.cache/node-gyp/20.18.1/include/node/node_buffer.h:25,
from ../src/BluetoothHciSocket.cpp:7:/home/iobroker/.cache/node-gyp/20.18.1/include/node/node.h:1232:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type] 1232 | (node::addon_register_func) (regfunc), \ | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/home/iobroker/.cache/node-gyp/20.18.1/include/node/node.h:1266:3: note: in expansion of macro ‘NODE_MODULE_X’ 1266 | NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage) | ^~~~~~~~~~~~~../src/BluetoothHciSocket.cpp:860:1: note: in expansion of macro ‘NODE_MODULE’ 860 | NODE_MODULE(binding, BluetoothHciSocket::Init); | ^~~~~~~~~~~
SOLINK_MODULE(target) Release/obj.target/bluetooth_hci_socket.node
COPY Release/bluetooth_hci_socket.node
COPY /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node
TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/build'
node-pre-gyp info ok
> @abandonware/noble@1.9.2-25 install> node-gyp-build
gyp info it worked if it ends with ok
gyp info using node-gyp@10.3.1gyp info using node@20.18.1 | linux | arm64
gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3gyp info spawn args [gyp info spawn args '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',gyp info spawn args 'binding.gyp',gyp info spawn args '-f',gyp info spawn args 'make',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/@abandonware/noble/build/config.gypi',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/node-gyp/addon.gypi',gyp info spawn args '-I',gyp info spawn args '/home/iobroker/.cache/node-gyp/20.18.1/include/node/common.gypi',gyp info spawn args '-Dlibrary=shared_library',gyp info spawn args '-Dvisibility=default',gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/20.18.1',gyp info spawn args '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/20.18.1/<(target_arch)/node.lib',gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/@abandonware/noble',gyp info spawn args '-Dnode_engine=v8',gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]
gyp info spawn makegyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/opt/iobroker/node_modules/@abandonware/noble/build' SOLINK_MODULE(target) Release/obj.target/noble.node
COPY Release/noble.node
gyp info ok
added 30 packages in 10s196 packages are looking for funding run `npm fund` for details
upload [4] switchbot-ble.admin /opt/iobroker/node_modules/iobroker.switchbot-ble/admin/admin.d.ts admin.d.ts video/mp2t
upload [2] switchbot-ble.admin /opt/iobroker/node_modules/iobroker.switchbot-ble/admin/style.css style.css text/css
upload [1] switchbot-ble.admin /opt/iobroker/node_modules/iobroker.switchbot-ble/admin/switchbot-ble.png switchbot-ble.png image/png
Updating objects from io-package.json for adapter "switchbot-ble" with version "0.4.9"
Process exited with code 0


Anlegen der Instanz:

$ iobroker add switchbot-ble auto --host iobroker --debug
host.iobroker create instance switchbot-ble
host.iobroker object system.adapter.switchbot-ble.0.alive created
host.iobroker object system.adapter.switchbot-ble.0.connected created
host.iobroker object system.adapter.switchbot-ble.0.compactMode created
host.iobroker object system.adapter.switchbot-ble.0.cpu created
host.iobroker object system.adapter.switchbot-ble.0.cputime created
host.iobroker object system.adapter.switchbot-ble.0.memHeapUsed created
host.iobroker object system.adapter.switchbot-ble.0.memHeapTotal created
host.iobroker object system.adapter.switchbot-ble.0.memRss created
host.iobroker object system.adapter.switchbot-ble.0.uptime created
host.iobroker object system.adapter.switchbot-ble.0.inputCount created
host.iobroker object system.adapter.switchbot-ble.0.eventLoopLag created
host.iobroker object system.adapter.switchbot-ble.0.sigKill created
host.iobroker object system.adapter.switchbot-ble.0.logLevel created
host.iobroker object switchbot-ble.0.info created
host.iobroker object switchbot-ble.0.info.connection created
host.iobroker Set default value of switchbot-ble.0.info.connection: false
host.iobroker object system.adapter.switchbot-ble.0 created
Process exited with code 0

**Comment by Track4123** [comment]
@mrbungle64, hattest du die Zeit nochmal meine Logs zu prüfen? Hat leider alles nichts geholfen😩, Problem ist immer noch, nicht nur bei mir.

**Comment by csch25** [comment]
Bei mir gleiches Problem wie bei @Track4123

**Comment by Track4123** [comment]
@mrbungle64 hier nochmal ein log wenn ich NPM Install mache.
Ne Idee? Grüße

iobroker@iobroker:/opt/iobroker/node_modules/iobroker.switchbot-ble $ npm instal                                                                              l
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memo                                                                              ry. Do not use it. Check out lru-cache if you want a good and tested way to coal                                                                              esce async requests by a key value, which is much more comprehensive and powerfu                                                                              l.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated lodash.get@4.4.2: This package is deprecated. Use the option                                                                              al chaining (?.) operator instead.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supp                                                                              orted
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supporte                                                                              d
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supporte                                                                              d
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated sinon@15.2.0: 16.1.1

**Comment by mrbungle64** [comment]
@Track4123 @csch25 @MagicPST 

Könnt Ihr bitte mal probieren, ob es mit der 0.4.10-alpha besser funktioniert?
Ich kann euer Problem nicht reproduzieren, weil es bei mir die ganze Zeit ohne Probleme funktioniert.

Bitte mit der URL https://github.com/mrbungle64/ioBroker.switchbot-ble/tree/alpha/4.9.10
und über die Oberfläche vom ioBroker Admin (Benutzerdefiniert: "Den Adapter von URL installieren oder aktualisieren")

**Comment by Track4123** [comment]
@mrbungle64 Danke! Habe die Version  0.4.10  installiert und es läuft jetzt wieder.
Habe wieder ein Verbindung zu den 2 Metern und dem Meter Plus. Habe den Adapter komplett deinstalliert und neu über GIP.
Scheint auch stabil zu laufen nach einem Neustart des Raspberry.
Was hast du geändert? Doch noch etwas gefunden? Viele Grüße!

**Comment by mrbungle64** [comment]
@Track4123 

> [@mrbungle64](https://github.com/mrbungle64) Danke! Habe die Version 0.4.10 installiert und es läuft jetzt wieder. Habe wieder ein Verbindung zu den 2 Metern und dem Meter Plus. Habe den Adapter komplett deinstalliert und neu über github. Scheint auch stabil zu laufen nach einem Neustart des Raspberry. 

Das freut mich

> Was hast du geändert? Doch noch etwas gefunden? Viele Grüße!

Ich habe nur diverse Dependencies auf den aktuellen Stand gebracht. Funktional habe ich nichts geändert.

**Comment by topherus** [comment]
I too am getting an error on install and the instance never changes green:

`$ iobroker url https://github.com/mrbungle64/ioBroker.switchbot-ble/tree/alpha/4.9.10 --host iobroker-pi --debug

install mrbungle64/ioBroker.switchbot-ble#alpha/4.9.10

NPM version: 11.3.0

Installing mrbungle64/ioBroker.switchbot-ble#alpha/4.9.10... (System call)

> usocket@0.3.0 install> node-gyp rebuild

gyp info it worked if it ends with ok

gyp info using node-gyp@7.1.2gyp info using node@20.19.1 | linux | arm64

gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"

gyp ERR! UNCAUGHT EXCEPTION

gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'gyp ERR! stack at createConfigFile (/opt/iobroker/node_modules/usocket/node_modules/node-gyp/lib/configure.js:117:21)gyp ERR! stack at /opt/iobroker/node_modules/usocket/node_modules/node-gyp/lib/configure.js:84:9gyp ERR! stack at FSReqCallback.oncomplete (node:fs:188:23)gyp ERR! System Linux 6.12.20+rpt-rpi-v8gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/usocket/node_modules/.bin/node-gyp" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/usocketgyp ERR! node -v v20.19.1gyp ERR! node-gyp -v v7.1.2gyp ERR! Node-gyp failed to build your package.gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.

added 30 packages, and changed 1 package in 19s

242 packages are looking for funding run `npm fund` for details

upload [4] switchbot-ble.admin /opt/iobroker/node_modules/iobroker.switchbot-ble/admin/admin.d.ts admin.d.ts video/mp2t

upload [3] switchbot-ble.admin /opt/iobroker/node_modules/iobroker.switchbot-ble/admin/index_m.html index_m.html text/html

upload [2] switchbot-ble.admin /opt/iobroker/node_modules/iobroker.switchbot-ble/admin/style.css style.css text/css

upload [1] switchbot-ble.admin /opt/iobroker/node_modules/iobroker.switchbot-ble/admin/switchbot-ble.png switchbot-ble.png image/png

upload [0] switchbot-ble.admin /opt/iobroker/node_modules/iobroker.switchbot-ble/admin/words.js words.js application/javascript

Updating objects from io-package.json for adapter "switchbot-ble" with version "0.4.10"

Process exited with code 0`
